###  API Personas
GET http://localhost:1234/persons/


###Recuperar por Rol
GET http://localhost:1234/persons?role=admin

###Recuperar por id peliculas
GET http://localhost:1234/persons/504015aa-b


### Crear Persona
POST http://localhost:1234/persons/
Content-Type: application/json

{
  "dni": "72345678",
  "password": "72345678",
  "firstname": "Mario",
  "lastname": "Uno",
  "email": "edwin@gmail.com",
  "birthdate": "2017-03-08T12:28:16.381Z",
  "gender": "Masculino",
  "address": "Calle 1 # 2-3",
  "mobilephone": "+514143857975",
  "homephone": "1234567890",
  "blood_typing": "A+",
  "created": "2020-01-01T04:00:00.000Z",
  "picture_url": "https://images.freeimages.com/images/large-previews/ddf/tour-d-eiffel-1447025.jpg",
  "role_id": 1
}

### ACTUALIZAR pelicuas 
PATCH http://localhost:1234/persons/510f2108-a6e9-47f2-a856-1161941851ef
Content-Type: application/json

{
  "dni": "72345678",
  "password": "72345678",
  "firstname": "Mario Editado",
  "lastname": "Uno",
  "email": "edwin@gmail.com",
  "birthdate": "1988-03-08T12:28:16.381Z",
  "gender": "Masculino",
  "address": "Calle 1 # 2-3",
  "mobilephone": "+514143857975",
  "homephone": "1234567890",
  "blood_typing": "A+",
  "created": "2020-01-01T04:00:00.000Z",
  "picture_url": "https://images.freeimages.com/images/large-previews/ddf/tour-d-eiffel-1447025.jpg",
  "role_id": 1
}

###Borrar pelicula
DELETE  http://localhost:1234/persons/510f2108-a6e9-47f2-a856-1161941851ef

