###  API Examas
GET http://localhost:1234/exams/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb24iOlsiMGVjNWQwM2ItNjhjZi00M2IwLTkyY2YtNzYxMWMwZTY2M2RkIiwxXSwiaWF0IjoxNzAxMzE1OTU1LCJleHAiOjE3MDEzMTY3OTV9.DoGRptNlcyaG0i_y3_FDIKv9QE2moNSsd-e-n4YiDDw

###Recuperar por Rol
GET http://localhost:1234/exams?_category=1

###Recuperar por id examens
GET http://localhost:1234/exams/0ec5d03b-68cf-43b0-92cf-7611c0e663dd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb24iOlsiMGVjNWQwM2ItNjhjZi00M2IwLTkyY2YtNzYxMWMwZTY2M2RkIiwxXSwiaWF0IjoxNzAxMjk1MjkwLCJleHAiOjE3MDEyOTYxMzB9.2El5oZDooPC2zB3KDV_STIcXJk8XBOfvHR2Fwfkh1l8


### Crear Exama
POST http://localhost:1234/exams/
Content-Type: application/json

{
  "dni": "1111",
  "password": "1234",
  "firstname": "Mario",
  "lastname": "Uno",
  "email": "edwin@gmail.com",
  "birthdate": "2017-03-08T12:28:16.381Z",
  "gender": "Masculino",
  "address": "Calle 1 # 2-3",
  "mobilephone": "+514143857975",
  "homephone": "1234567890",
  "blood_typing": "A+",
  "created": "2020-01-01T04:00:00.000Z",
  "picture_url": "https://images.freeimages.com/images/large-previews/ddf/tour-d-eiffel-1447025.jpg",
  "role_id": 1
}

### ACTUALIZAR pelicuas 
PATCH http://localhost:1234/exams/510f2108-a6e9-47f2-a856-1161941851ef
Content-Type: application/json

{
  "dni": "72345678",
  "password": "72345678",
  "firstname": "Mario Editado",
  "lastname": "Uno",
  "email": "edwin@gmail.com",
  "birthdate": "1988-03-08T12:28:16.381Z",
  "gender": "Masculino",
  "address": "Calle 1 # 2-3",
  "mobilephone": "+514143857975",
  "homephone": "1234567890",
  "blood_typing": "A+",
  "created": "2020-01-01T04:00:00.000Z",
  "picture_url": "https://images.freeimages.com/images/large-previews/ddf/tour-d-eiffel-1447025.jpg",
  "role_id": 1
}

###Borrar examen
DELETE  http://localhost:1234/exams/{ID}

